.TH MERGER "1" "January 2018" "2.6.1 merger" "User Commands"
.SH NAME
merger \- manual page for merger 2.6.1
.SH SYNOPSIS
.B merger
[\fICOMMON\fR]... [\fIOPTIONS\fR]...
.SH DESCRIPTION
.TP
Number of Input IFC: \fBvariable\fR
..
.TP
Number of Output IFC: \fB1\fR
..
.TP
This module merges traffic from multiple input interfaces to one output stream (on one interface).
.HP
\fB\-u\fR, \fB\-\-unirec\fR
UniRec specifier of input/output data (same to all links). (default <COLLECTOR_FLOW>).
.TP
\fB\-F\fR, \fB\-\-time_first\fR
(timestamp aware version) Sorts timestamps based on TIME_FIRST field
.TP
\fB\-T\fR, \fB\-\-timestamp\fR
Set mode to timestamp aware (not by default).
.TP
\fB\-n\fR, \fB\-\-link_count\fR
Sets count of input links. Must correspond to parameter -i (trap).
.TP
\fB\-t\fR, \fB\-\-timeout\fR
(timestamp aware version) Set initial timeout for incoming interfaces (in seconds). Timeout is set to 0
.TP
.SH COMMON OPTIONS:
.TP
\fB\-h\fR \fB[trap,1]\fR
If no argument, print this message. If \fItrap\fR or 1 is given, print TRAP help.
.TP
\fB\-i\fR \fBIFC_SPEC\fR
Specification of interface types and their parameters, see \fI\-h trap\fR (mandatory parameter).
.TP
\fB\-v\fR
Be verbose.
.TP
\fB\-vv\fR
Be more verbose.
.TP
\fB\-vvv\fR
Be even more verbose.
.SH ENVIRONMENT VARIABLES
.TP
\fBPAGER\fR
Show the help output in the set \fBPAGER\fR.
.TP
\fBLIBTRAP_OUTPUT_FORMAT\fR
If set to \fIjson\fR, information about module is printed in JSON format.
.TP
\fBTRAP_SOCKET_DIR\fR
Redefines directory for UNIX sockets.
.SH BUGS
Please send problems, bugs, questions, desirable enhancements, patches etc. to:
\fInemea@cesnet.cz\fR

