.TH LOGREPLAY "1" "January 2018" "2.6.1 logreplay" "User Commands"
.SH NAME
logreplay \- manual page for logreplay 2.6.1
.SH SYNOPSIS
.B logreplay
[\fICOMMON\fR]... [\fIOPTIONS\fR]...
.SH DESCRIPTION
.TP
Number of Input IFC: \fB0\fR
..
.TP
Number of Output IFC: \fB1\fR
..
.TP
This module converts CSV from logger and sends it in UniRec. The first row of CSV file has to be data format of fields.
.HP
\fB\-n\fR, \fB\-\-no_eof\fR
Don't send 'EOF message' at the end.
.TP
\fB\-c\fR, \fB\-\-cut\fR
Quit after N records are received.
.TP
\fB\-d\fR, \fB\-\-disable_timing\fR
Disable time delays during sending data according to the `time` column.
.TP
\fB\-f\fR, \fB\-\-file\fR
Specify path to a file to be read.
.TP
.SH COMMON OPTIONS:
.TP
\fB\-h\fR \fB[trap,1]\fR
If no argument, print this message. If \fItrap\fR or 1 is given, print TRAP help.
.TP
\fB\-i\fR \fBIFC_SPEC\fR
Specification of interface types and their parameters, see \fI\-h trap\fR (mandatory parameter).
.TP
\fB\-v\fR
Be verbose.
.TP
\fB\-vv\fR
Be more verbose.
.TP
\fB\-vvv\fR
Be even more verbose.
.SH ENVIRONMENT VARIABLES
.TP
\fBPAGER\fR
Show the help output in the set \fBPAGER\fR.
.TP
\fBLIBTRAP_OUTPUT_FORMAT\fR
If set to \fIjson\fR, information about module is printed in JSON format.
.TP
\fBTRAP_SOCKET_DIR\fR
Redefines directory for UNIX sockets.
.SH BUGS
Please send problems, bugs, questions, desirable enhancements, patches etc. to:
\fInemea@cesnet.cz\fR

