.TH DEVICE CLASSIFIER "1" "January 2018" "2.6.1 Device classifier" "User Commands"
.SH NAME
Device classifier \- manual page for Device classifier 2.6.1
.SH SYNOPSIS
.B device classifier
[\fICOMMON\fR]... [\fIOPTIONS\fR]...
.SH DESCRIPTION
.TP
Number of Input IFC: \fB1\fR
..
.TP
Number of Output IFC: \fB0\fR
..
.TP
Module classifies devices according to their network behavior.
.HP
\fB\-l\fR, \fB\-\-list\fR
Print a list of known labels and exit.
.TP
\fB\-m\fR, \fB\-\-minutes\fR
Period after which the output is generated (default 0 = no period)
.TP
\fB\-F\fR, \fB\-\-file\fR
Save results to JSON file given as parameter.
.TP
\fB\-a\fR, \fB\-\-accumulate\fR
Do not discard collected statistics each time the output is generated.
.TP
\fB\-p\fR, \fB\-\-peers\fR
Add only devices with equal or greater number of peers to output.
.TP
\fB\-f\fR, \fB\-\-filter\fR
Classify only IP addresses (or subnets) specified in file given as parameter.
.TP
\fB\-t\fR, \fB\-\-train\fR
Run in a training mode. Training rules are specified in file given as parameter.
.TP
.SH COMMON OPTIONS:
.TP
\fB\-h\fR \fB[trap,1]\fR
If no argument, print this message. If \fItrap\fR or 1 is given, print TRAP help.
.TP
\fB\-i\fR \fBIFC_SPEC\fR
Specification of interface types and their parameters, see \fI\-h trap\fR (mandatory parameter).
.TP
\fB\-v\fR
Be verbose.
.TP
\fB\-vv\fR
Be more verbose.
.TP
\fB\-vvv\fR
Be even more verbose.
.SH ENVIRONMENT VARIABLES
.TP
\fBPAGER\fR
Show the help output in the set \fBPAGER\fR.
.TP
\fBLIBTRAP_OUTPUT_FORMAT\fR
If set to \fIjson\fR, information about module is printed in JSON format.
.TP
\fBTRAP_SOCKET_DIR\fR
Redefines directory for UNIX sockets.
.SH BUGS
Please send problems, bugs, questions, desirable enhancements, patches etc. to:
\fInemea@cesnet.cz\fR

